name: Quarto

on: workflow_dispatch

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
      - run: npm run check
      - run: npm run render
      - uses: EndBug/add-and-commit@v10
        with:
          message: 'chore: render quarto artefacts'
